httplug:
    plugins:
        redirect:
            preserve_header: true

    discovery:
        client: 'auto'

    clients:
        meetup:
            http_methods_client: true
            plugins:
                - 'httplug.plugin.logger'
                - 'httplug.plugin.redirect'
                - add_host: { host: 'https://api.meetup.com' }
        app:
            http_methods_client: true
            plugins:
                - 'httplug.plugin.content_length'
                - 'httplug.plugin.redirect'
