version: '3'

services:
  php:
    container_name: php
    build:
        context: ./docker/php
    links:
      - mysql
      - blackfire
    volumes:
      - .:/opt/flex-meetup:cached
    environment:
      - DATABASE_URL=mysql://dbuser:dbpass@mysql/meetup
      - BLACKFIRE_CLIENT_ID
      - BLACKFIRE_CLIENT_TOKEN

  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: meetup
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    volumes:
      - .:/opt/flex-meetup:cached
    links:
      - php
    ports:
      - 80:80

  blackfire:
    container_name: blackfire
    image: blackfire/blackfire
    environment:
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN

volumes:
  db_data:
